title: Cafeteria Tematica
email: yanelahurtadohuaringa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Cafeteria tematica es un lugar donde encontraras un ambiente calido donde podras
 disfrutar de los platos de la epoca de los 50.
baseurl: "/miNuevoSitio" # the subpath of your site, e.g. /blog
url: "https://yanehh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yanehh
github_username:  yanehh

# Build settings
theme: minima
plugins:
  - jekyll-feed
  

